### ISSUE TITLE
Change the font size

### ISSUE THREAD

**Issue by priyasirohi09** [priyasirohi09/talawa-admin#1]
**Describe the bug**

**To Reproduce**

1.
2.
3.
4.

**Expected behavior**

**Actual behavior**
A clear and concise description of how the code performed w.r.t expectations.

**Screenshots**

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by narasimha-1511** [comment]
hey @priyasirohi09  
i did not get the bug just the titlle is Change the font size ?
